AarhusWebDevelopersNetwork/ViewModels/ContactForm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace AarhusWebDevelopersNetwork.ViewModels
{
    public class ContactForm
    {
        [Required]
        public string Name { get; set; }

        [Required]
        [EmailAddress(ErrorMessage = "This is not a valid email address")]
        public string Email { get; set; }

        [Required]
        public string Subject { get; set; }

        [Required]
        public string Message { get; set; }
    }
}

AarhusWebDevelopersNetwork/ViewModels/Message.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace AarhusWebDevelopersNetwork.ViewModels
{
    public class Message
    {
        [Required]
        public string Name { get; set; }

        [Required]
        public string MessageText { get; set; }
    }
}

AarhusWebDevelopersNetwork/Controllers/ContactFormSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using AarhusWebDevelopersNetwork.ViewModels;
using System.Net.Mail;
using Umbraco.Core.Models;

namespace AarhusWebDeveopersNetwork.Controllers
{
    public class ContactFormSurfaceController : SurfaceController
    {
        // GET: ContactFormSurface
        public ActionResult Index()
        {
            return PartialView("ContactForm", new ContactForm());
        }

        [HttpPost]
        public ActionResult HandleFormSubmit(ContactForm model)
        {

            if (!ModelState.IsValid)
            {

                return CurrentUmbracoPage();

            }

            MailMessage message = new MailMessage();
            message.To.Add("aboesig@gmail.com");
            message.Subject = model.Subject;
            message.From = new MailAddress(model.Email, model.Name);
            message.Body = model.Message + "\n my email is: " + model.Email;

            using (SmtpClient smtp = new SmtpClient())
            {
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network; smtp.UseDefaultCredentials = false;
                smtp.EnableSsl = true;
                smtp.Host = "smtp.gmail.com"; smtp.Port = 587;
                smtp.Credentials = new System.Net.NetworkCredential("aboesig@gmail.com", "ptealhtmayulmacw");
                smtp.EnableSsl = true;

                smtp.Send(message);
            }

            IContent comment = Services.ContentService.CreateContent(model.Subject, CurrentPage.Id, "Comment");

            comment.SetValue("commentName", model.Name);
            comment.SetValue("commentEmail", model.Email);
            comment.SetValue("commentSubject", model.Subject);
            comment.SetValue("commentMessage", model.Message);

            Services.ContentService.SaveAndPublishWithStatus(comment);

            TempData["Succes"] = true;
            return RedirectToCurrentUmbracoPage();
        }
    }
}

AarhusWebDevelopersNetwork/Controllers/MessageBoardSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using AarhusWebDevelopersNetwork.ViewModels;
using System.Web.Mvc;
using Umbraco.Core.Models;
using Umbraco.Web.Mvc;

namespace AarhusWebDevelopersNetwork.Controllers
{
    public class MessageBoardSurfaceController : SurfaceController
    {
        // GET: MessageFormSurface
        public ActionResult Index()
        {
            return PartialView("MessageForm", new Message());
        }

        private void CreateAndSaveMessage(Message model)
        {
            IContent message = Services.ContentService.CreateContent(model.Name, CurrentPage.Id, "Message");
            // assign values
            message.SetValue("messageName", model.Name);
            message.SetValue("messageMessage", model.MessageText);

            Services.ContentService.SaveAndPublishWithStatus(message);
        }

        [HttpPost]
        public ActionResult HandleFormSubmit(Message model)
        {
            if (!ModelState.IsValid)
            {
                return CurrentUmbracoPage();
            }

            CreateAndSaveMessage(model);

            return RedirectToCurrentUmbracoPage();
        }

    }
}

AarhusWebDevelopersNetwork/Views/ArticlesItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ArticleItem>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}
@CurrentPage.GetGridHtml(Html, "articleItemGrid")

AarhusWebDevelopersNetwork/Views/ArticlesMain.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ArticlesMain>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}
<div class="container">
    <!-- Jumbotron Header -->
    <header class="jumbotron hero-spacer">
        @Umbraco.Field("articlesMainText")
    </header>
</div>
<div class="container">
	@Html.Partial("listArticles")
</div>

AarhusWebDevelopersNetwork/Views/ContactPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}
<div class="container">
    <!-- Jumbotron Header -->
    <header class="jumbotron hero-spacer">
        @Umbraco.Field("contactPageText")
    </header>
</div>
<div class="container">
    @Html.Action("Index", "ContactFormSurface")
</div>

AarhusWebDevelopersNetwork/Views/Homepage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Homepage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "Master.cshtml";
}
<div class="container">
    <!-- Jumbotron Header -->
    <header class="jumbotron hero-spacer">
        @Umbraco.Field("homepageText")
        <p>
            <a href="/projects" class="btn btn-primary btn-large">Check our Projects</a>
        </p>
    </header>
    <!-- Title -->
    <div class="row">
        <div class="col-lg-12">
            <h3>Latest projects</h3>
        </div>
    </div>
    @Html.Partial("listProjectsFrontpage")
</div>

AarhusWebDevelopersNetwork/Views/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "Master.cshtml";
}
<div class="container">
    @if (!Members.GetCurrentLoginStatus().IsLoggedIn)
    {
        @Html.Partial("Login")
    }
    else
    {
        @Html.Partial("Logout")
    }
</div>

AarhusWebDevelopersNetwork/Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="@Umbraco.Field("metaDescription")">
    <meta name="keywords" content="@Umbraco.Field("metaKeywords")">
    <title>@Umbraco.Field("siteTitle", recursive: true)</title>
    <!-- Bootstrap core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <!-- Custom styles -->
    <link href="~/css/style.css" rel="stylesheet" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">@Umbraco.Field("siteTitle", recursive: true)</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                @Html.Partial("menuPartial");
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <!-- Page Content -->
    @RenderBody()

    <div class="container">
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>@Umbraco.Field("footer", recursive: true)</p>
                </div>
            </div>
        </footer>
    </div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="~/Scripts/jquery-1.9.1.min.js"><\/script>')</script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
</body>
</html>

AarhusWebDevelopersNetwork/Views/Members.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Members>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}
<div class="container">
    <!-- Jumbotron Header -->
    <header class="jumbotron hero-spacer">
        @Umbraco.Field("memberPageText")
    </header>
</div>
<div class="container">
	@Html.Partial("displayMembers")
</div>

AarhusWebDevelopersNetwork/Views/MessageBoard.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.MessageBoard>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}
<div class="container">
    <!-- Jumbotron Header -->
    <header class="jumbotron hero-spacer">
        @Umbraco.Field("messageBoardText")
    </header>
</div>
<div class="container">
	<div class="col-sm-6">
    @Html.Action("Index", "MessageBoardSurface")
	</div>
	<div class="col-sm-6">
	@Html.Partial("displayMessages")
	</div>
</div>

AarhusWebDevelopersNetwork/Views/Optionals.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Optionals>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

AarhusWebDevelopersNetwork/Views/Partials/ContactForm.cshtml
@model AarhusWebDevelopersNetwork.ViewModels.ContactForm

@if (TempData["Succes"] == null)
{

    using (Html.BeginUmbracoForm("HandleFormSubmit", "ContactFormSurface", new Object { }, new { @class = "form-horizontal" }))
    {
        <div class="form-group">
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email" })
                @Html.ValidationMessageFor(m => m.Email)
            </div>
        </div>
            <div class="form-group">
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.Subject, new { @class = "form-control", placeholder = "Subject" })
                    @Html.ValidationMessageFor(m => m.Subject)
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Name" })
                    @Html.ValidationMessageFor(m => m.Name)
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-6">
                    @Html.TextAreaFor(m => m.Message, new { @class = "form-control", placeholder = "Message" })
                    @Html.ValidationMessageFor(m => m.Message)
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-6">
                    <button type="submit" class="btn btn-success">Send message</button>
                </div>
            </div>
    }
}
else
{
    <p>Thank you for contacting us, we will be in touch soon!</p>
}

AarhusWebDevelopersNetwork/Views/Partials/Grid/Bootstrap2.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "=\"" + property.Value.ToString() + "\"");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style=\"" + string.Join(" ", cssVals) + "\"");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

AarhusWebDevelopersNetwork/Views/Partials/Grid/Bootstrap3.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="col-md-@s.grid column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "=\"" + property.Value.ToString() + "\"");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style=\"" + string.Join(" ", cssVals) + "\"");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

AarhusWebDevelopersNetwork/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

AarhusWebDevelopersNetwork/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates
@Html.Raw(Model.value)

AarhusWebDevelopersNetwork/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

AarhusWebDevelopersNetwork/Views/Partials/Grid/Editors/Media.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.value != null)
{   
    var url = Model.value.image;
    if(Model.editor.config != null && Model.editor.config.size != null){
        url += "?width=" + Model.editor.config.size.width;
        url += "&height=" + Model.editor.config.size.height;

        if(Model.value.focalPoint != null){
            url += "&center=" + Model.value.focalPoint.top +"," + Model.value.focalPoint.left;
            url += "&mode=crop";
        }
    }
    
    <img src="@url" alt="@Model.value.altText">
    
    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}

AarhusWebDevelopersNetwork/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString()))

AarhusWebDevelopersNetwork/Views/Partials/Grid/Editors/Textstring.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.editor.config.markup != null)
{
    string markup = Model.editor.config.markup.ToString();

    var UmbracoHelper = new UmbracoHelper(UmbracoContext.Current);
    
    markup = markup.Replace("#value#", UmbracoHelper.ReplaceLineBreaksForHtml(Model.value.ToString()));
    markup = markup.Replace("#style#", Model.editor.config.style.ToString());

    <text>
        @Html.Raw(markup)
    </text>
}
else
{
    <text>
        <div style="@Model.editor.config.style">@Model.value</div>
    </text>
}

AarhusWebDevelopersNetwork/Views/Partials/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage


@using System.Web.Mvc.Html
@using ClientDependency.Core.Mvc
@using Umbraco.Web
@using Umbraco.Web.Models
@using Umbraco.Web.Controllers

@{
    var loginModel = new LoginModel();

    Html.EnableClientValidation();
    Html.EnableUnobtrusiveJavaScript();
    Html.RequiresJs("/umbraco_client/ui/jquery.js");
    Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.min.js");
    Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.unobtrusive.min.js");
}

@* NOTE: This RenderJsHere code should be put on your main template page where the rest of your script tags are placed *@
@Html.RenderJsHere()

<div class="container">

    @using (Html.BeginUmbracoForm<UmbLoginController>("HandleLogin"))
    {
        <fieldset>
            <legend>Login</legend>

            @Html.ValidationSummary("loginModel", true)

            <div class="col-sm-6">
                @Html.TextBoxFor(m => loginModel.Username, new { @class = "form-control", placeholder = "Name" })
                @Html.ValidationMessageFor(m => loginModel.Username)
            </div>
            <div class="col-sm-6">
                @Html.PasswordFor(m => loginModel.Password, new { @class = "form-control", placeholder = "Password" })
                @Html.ValidationMessageFor(m => loginModel.Password)
            </div>
            <div class="col-sm-6">
                <button style="margin-top: 15px;" class="btn btn-success">Login</button>
            </div>
        </fieldset>

    }
</div>

AarhusWebDevelopersNetwork/Views/Partials/Logout.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using System.Web.Mvc.Html
@using ClientDependency.Core.Mvc
@using Umbraco.Web
@using Umbraco.Web.Models
@using Umbraco.Web.Controllers
@{
    var loginStatusModel = Members.GetCurrentLoginStatus();

    Html.EnableClientValidation();
    Html.EnableUnobtrusiveJavaScript();
    Html.RequiresJs("/umbraco_client/ui/jquery.js");
    Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.min.js");
    Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.unobtrusive.min.js");

    var logoutModel = new PostRedirectModel();

    @*
        Here you can specify a redirect URL for after logging out, by default umbraco will simply
        redirect to the current page. Example to redirect to the home page:

        logoutModel.RedirectUrl = "/";
    *@
}
@* NOTE: This RenderJsHere code should be put on your main template page where the rest of your script tags are placed *@
@Html.RenderJsHere()
@if (loginStatusModel.IsLoggedIn)
{
    <p>You are currently logged in as @loginStatusModel.Name</p>

    using (Html.BeginUmbracoForm<UmbLoginStatusController>("HandleLogout"))
    {
        <div class="container">
            <fieldset>
                <legend>Logout</legend>
                <div class="col-sm-6">
                    <button style="margin-top: 15px;" class="btn btn-success">Logout</button>
                </div>
            </fieldset>
        </div>
        @Html.HiddenFor(m => logoutModel.RedirectUrl)
    }
}

AarhusWebDevelopersNetwork/Views/Partials/MessageForm.cshtml
@model AarhusWebDevelopersNetwork.ViewModels.Message

@using(Html.BeginUmbracoForm<AarhusWebDevelopersNetwork.Controllers.MessageBoardSurfaceController>
    ("HandleFormSubmit") )
{

        <div class="form-group">
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Name" })
                @Html.ValidationMessageFor(m => m.Name)
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-6">
                @Html.TextAreaFor(m => m.MessageText, new { @class = "form-control", placeholder = "Message" })
                @Html.ValidationMessageFor(m => m.MessageText)
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-6">
                <button type="submit" class="btn btn-success">Send message</button>
            </div>
        </div>
    }

AarhusWebDevelopersNetwork/Views/Partials/displayMembers.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    var memberService = ApplicationContext.Current.Services.MemberService;

    var membersActive = memberService.GetMembersByGroup("Active");
    var membersProspect = memberService.GetMembersByGroup("Prospects");
}
<div class="container">
    <h2>Active members</h2>
    @foreach (var member in membersActive)
    {

        string fullPath = member.GetValue("photo").ToString();
        string[] substrings = fullPath.Split(',');
        string srcString = substrings[2];
        string[] srcSubStrings = srcString.Split(':');
        string srcPath = srcSubStrings[1].Replace("\"", "");
        srcPath = srcPath.Replace("}", "");

        <div class="col-md-3 col-sm-6 hero-feature">
            <div class="thumbnail">
                <img class="img-responsive" src="@srcPath" />
                <div class="caption">
                    <h3>@(member.GetValue("firstname") + " " + member.GetValue("lastname"))</h3>
                    <strong>Address:</strong> @member.GetValue("address")<br />
                    @(member.GetValue("zip") + " "
                    + member.GetValue("city"))<br />
                    <strong>Mobile:</strong> @member.GetValue("mobile")<br />
                </div>
            </div>
        </div>
    }
</div>
<div class="container">
    <h2>Prospects</h2>
    <div>
        @foreach (var prospect in membersProspect)
        {
            <div class="well col-sm-4">
                @(prospect.GetValue("firstname") + " " + prospect.GetValue("lastname")) - Mobile: @prospect.GetValue("mobile")
            </div>
        }
    </div>
</div>

AarhusWebDevelopersNetwork/Views/Partials/displayMessages.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage

@{ var selection = CurrentPage.Children.Where("Visible").OrderBy("CreateDate desc").Take(3); }

<div>
    @foreach (var item in selection)
    {
        <div class="text-muted">@item.CreateDate</div>
        <div class="well"><strong>@item.Name:</strong> @item.messageMessage</div>
    }
</div>

AarhusWebDevelopersNetwork/Views/Partials/listArticles.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage

@{ var selection = CurrentPage.Children.Where("Visible").OrderBy("CreateDate desc"); }

<div class="row">
    @foreach (var item in selection)
    {
        <div class="col-md-3 col-sm-6 hero-feature">
            <div class="thumbnail">
                <img src="@item.GetCropUrl("articleImage", "Thumbnail")" />
                <div class="caption">
                    <h3>@item.Name</h3>
                    <p>
                        <a href="@item.Url" class="btn btn-primary">Read more</a>
                    </p>
                </div>
            </div>
        </div>
    }
</div>

AarhusWebDevelopersNetwork/Views/ProjectItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ProjectItem>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}
@CurrentPage.GetGridHtml(Html, "projectItemGrid")

AarhusWebDevelopersNetwork/Views/TextPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.TextPage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "Master.cshtml";
}

@CurrentPage.GetGridHtml(Html, "gridLayout")